### ISSUE TITLE
Error on running project using yarn docker:dev

### ISSUE THREAD

**Issue by pedroodb** [ulises-jeremias/react-webpack-starter#24]
**React + Webpack Starter version:** 1.22.4

**OS:** Ubuntu 20.04
**NodeJs version: 12.16.3**

I created a project using the command and the flags: `--typescript --redux --saga --docker --antd` and then from the project folder run `yarn docker:dev`. It failed to compile showing this output:

    ERROR in ./src/components/Animation/slicer.scss (./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/sass-loader/dist/cjs.js!./src/components/Animation/slicer.scss)

    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: Missing binding /usr/src/app/node_modules/node-sass/vendor/linux_musl-x64-72/binding.node
    Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 12.x
    
    Found bindings for the following environments:
      - Linux 64-bit with Node.js 12.x
    
    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass` to download the binding for your current environment.
        at module.exports (/usr/src/app/node_modules/node-sass/lib/binding.js:15:13)
        at Object.<anonymous> (/usr/src/app/node_modules/node-sass/lib/index.js:14:35)
        at Module._compile (internal/modules/cjs/loader.js:955:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
        at Module.load (internal/modules/cjs/loader.js:811:32)
        at Function.Module._load (internal/modules/cjs/loader.js:723:14)
        at Module.require (internal/modules/cjs/loader.js:848:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at getDefaultSassImplementation (/usr/src/app/node_modules/sass-loader/dist/utils.js:42:10)
        at getSassImplementation (/usr/src/app/node_modules/sass-loader/dist/utils.js:50:30)
        at Object.loader (/usr/src/app/node_modules/sass-loader/dist/index.js:34:59)

Same happened using `--semantic-ui` flag instead of `--antd`.
The project runs fine when not using docker (using `yarn start`)

Possible solution found [here](https://github.com/sass/node-sass/issues/2165)

**Comment by ulises-jeremias** [comment]
Hi @pedroodb ! I just solved this bug updating the Dockerfile generated in the presence of `--docker` flag. The bugfix is now available in `v1.2.4`. Thanks for the contribution!
